name: fmri-aging
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - statsmodels
  - nilearn
  - nibabel
  - jupyterlab
  - pip
  - pip:
      - openneuro-py
      - fmriprep-docker